### ISSUE TITLE
关于蒸馏Vit的问题

### ISSUE THREAD

**Issue by Nick32625** [sunshangquan/logit-standardardization-KD#10]
请问蒸馏vit的代码是各个蒸馏方法通用的吗？另外，请问vit可以作为教师模型吗

**Comment by Death-void** [comment]
另外，请问蒸馏vit的实验怎么复现呀？

**Comment by sunshangquan** [comment]
蒸馏ViT的算法我们只写了KD和KD+Ours的代码，其他的算法可能会遇到“参数不合适”等问题，比如我们尝试过DKD，默认参数下效果最后KD差不多；ViT作为教师应该是可行的，不过我们是在cvpr的rebuttal阶段才做的实验，因为在cifar100数据集太小了(直接from scract训练的vit效果不好)，在cifar100上预训练的ViT几乎没有，所以用的是cnn做教师。

For the algorithm of distilling ViT, we only wrote the code of KD and KD+Ours. Other algorithms may encounter problems such as "inappropriate parameters". For example, we tried DKD, and the effect was similar to KD under the default parameters; 
It should be feasible for ViT to be a teacher, but we only did the experiment in the rebuttal stage of cvpr. Because the cifar100 data set is small for training ViT from scratch, and thus there are almost no ViT model pre-trained on cifar100, we use cnn as the teacher.

**Comment by Nick32625** [comment]
好的，非常感谢您
