### ISSUE TITLE
CTKD  --logit_stand question

### ISSUE THREAD

**Issue by eminentgu** [sunshangquan/logit-standardardization-KD#15]
In your code at logit-standardization-KD/CTKD/train_student.py, u have `parser.add_argument('--logit_stand',action='store_true')` ,which I suppose when I use  --logit_stand it will use logit stand,  however ,it writes `criterion_div = DistillKL() if opt.logit_stand else DistillKL_logit_stand()`, which confuses me for what I understand is opposite, when I use --logit_stand, it uses DistillKL(). and the reproduce result is:  without  --logit_stand is better than with  --logit_stand. Any idea? let me know

**Comment by sunshangquan** [comment]
Hi @eminentgu , thank you for your reminder. The code here for CTKD is opposite, but the results should be fine because the experiments conducted before were not based on the current version, and I will fix this soon. Regarding your reproduction, could you please let me know more details on configurations, like stu/tea pairs and hyper-parameters? I will then check the settings I provide.

**Comment by eminentgu** [comment]
hey thx for reply. In that case, it is fine, so  just a minor issue on the code side. I tried both experiments with/without --logit_stand and left others default and the results do show an improvement with logit_stand. So tl;dr : nothing is wrong except a minor code issue, I fixed it myself and it doesn't affect the result at all. Anyway thx again for your great work and your effort, I will then close this issue, good day :)
